/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * EduConnect
 * This is a social media for students
 * Service version: 1.0.0
 */
import { FormData } from "https://jslib.k6.io/formdata/0.0.2/index.js";

import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;

/**
 * @nullable
 */
export type UserAcademicYear =
  | (typeof UserAcademicYear)[keyof typeof UserAcademicYear]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserAcademicYear = {
  L1: "L1",
  L2: "L2",
  L3: "L3",
  M1: "M1",
  M2: "M2",
  D1: "D1",
  D2: "D2",
  D3: "D3",
  D4: "D4",
  D5: "D5",
} as const;

export interface User {
  /** The user ID */
  id?: string;
  /** The user's username */
  username?: string;
  /** The user's email */
  email?: string;
  firstName?: string;
  lastName?: string;
  /**
   * User biography
   * @nullable
   */
  bio?: string | null;
  role?: UserRole;
  /** @nullable */
  academicYear?: UserAcademicYear;
  /** @nullable */
  profilePhoto?: string | null;
  /** @nullable */
  specialityId?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export type AuthResponseData = {
  accessToken?: string;
  refreshToken?: string;
  user?: User;
};

export interface AuthResponse {
  success?: boolean;
  message?: string;
  data?: AuthResponseData;
}

export interface Comment {
  /** The comment ID */
  id?: string;
  /** The ID of the post the comment belongs to */
  postId?: string;
  /** The ID of the user who created the comment */
  userId?: string;
  /** The content of the comment */
  content?: string;
  /** Soft delete flag */
  isDeleted?: boolean;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
}

export interface Faculty {
  /** The faculty ID */
  id?: string;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
}

export type PostPostType = (typeof PostPostType)[keyof typeof PostPostType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPostType = {
  QUESTION: "QUESTION",
  ANSWER: "ANSWER",
  ANNOUNCEMENT: "ANNOUNCEMENT",
  STUDY_TIP: "STUDY_TIP",
  EXPLANATION: "EXPLANATION",
  RESOURCE: "RESOURCE",
  PDF_RESOURCE: "PDF_RESOURCE",
  SUMMARY: "SUMMARY",
  AI_SUMMARY: "AI_SUMMARY",
  AI_QUESTION: "AI_QUESTION",
  POLL: "POLL",
  DISCUSSION: "DISCUSSION",
  EVENT: "EVENT",
} as const;

export interface Post {
  /** The post ID */
  id?: string;
  /** The ID of the user who created the post */
  userId?: string;
  /**
   * The title of the post
   * @nullable
   */
  title?: string | null;
  /** The content of the post */
  content?: string;
  postType?: PostPostType;
  /** Number of reactions */
  reactionCount?: number;
  /** Number of comments */
  commentCount?: number;
  /** Soft delete flag */
  isDeleted?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * The type of reaction
 */
export type ReactionReactionType =
  (typeof ReactionReactionType)[keyof typeof ReactionReactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReactionReactionType = {
  LIKE: "LIKE",
  HELPFUL: "HELPFUL",
  EASY: "EASY",
  TOUGH: "TOUGH",
  FIRE: "FIRE",
  MIND_BLOWN: "MIND_BLOWN",
} as const;

export interface Reaction {
  /** The reaction ID */
  id?: string;
  /** The ID of the user who reacted */
  userId?: string;
  /** The ID of the post reacted to */
  postId?: string;
  /** The type of reaction */
  reactionType?: ReactionReactionType;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
}

export interface Specialty {
  /** The specialty ID */
  id?: string;
  /** Full name of the specialty */
  name?: string;
  /** Short name or abbreviation */
  shortName?: string;
  /** Brief description of the specialty */
  description?: string;
  /** ID of the faculty this specialty belongs to */
  facultyId?: string;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
}

export interface University {
  /** The university ID */
  id?: string;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
}

export type PostAuthSignUpBody = {
  /** @maxLength 25 */
  firstName: string;
  /** @maxLength 25 */
  lastName: string;
  /**
   * @minLength 3
   * @maxLength 25
   */
  username: string;
  /** @maxLength 254 */
  email: string;
  /** @minLength 8 */
  password: string;
  /** @maxLength 200 */
  bio?: string;
};

export type PostAuthLoginBody = {
  email: string;
  password: string;
};

export type PostAuthLogoutBody = {
  /** The refresh token to invalidate */
  refreshToken: string;
};

export type PostAuthRefreshToken201 = {
  success?: boolean;
  message?: string;
};

export type GetCommentPostPostIdCommentsParams = {
  /**
   * Cursor for pagination
   */
  cursor?: string;
  /**
   * Number of items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetCommentPostPostIdComments200DataPagination = {
  hasNextPage?: boolean;
  /** @nullable */
  nextCursor?: string | null;
  count?: number;
};

export type GetCommentPostPostIdComments200Data = {
  comments?: Comment[];
  pagination?: GetCommentPostPostIdComments200DataPagination;
};

export type GetCommentPostPostIdComments200 = {
  success?: boolean;
  message?: string;
  data?: GetCommentPostPostIdComments200Data;
};

export type GetCommentId200 = {
  success?: boolean;
  message?: string;
  data?: Comment;
};

export type PutCommentIdBody = {
  /** The new content of the comment */
  content: string;
};

export type PutCommentId200 = {
  success?: boolean;
  message?: string;
  data?: Comment;
};

export type DeleteCommentId200 = {
  success?: boolean;
  message?: string;
  data?: Comment;
};

export type PostCommentPostIdBody = {
  /** The content of the comment */
  content: string;
};

export type PostCommentPostId201 = {
  success?: boolean;
  message?: string;
  data?: Comment;
};

export type GetFaculty200 = {
  success?: boolean;
  message?: string;
  data?: Faculty[];
};

export type PostFacultyBody = {
  exampleProperty?: string;
};

export type PostFaculty201 = {
  success?: boolean;
  message?: string;
  data?: Faculty;
};

export type GetFacultyId200 = {
  success?: boolean;
  message?: string;
  data?: Faculty;
};

export type PutFacultyIdBody = {
  exampleProperty?: string;
};

export type PutFacultyId200 = {
  success?: boolean;
  message?: string;
  data?: Faculty;
};

export type DeleteFacultyId200 = {
  success?: boolean;
  message?: string;
};

export type GetPostsParams = {
  /**
   * Cursor for pagination
   */
  cursor?: string;
  /**
   * Number of items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetPosts200DataPagination = {
  hasNextPage?: boolean;
  /** @nullable */
  nextCursor?: string | null;
  count?: number;
};

export type GetPosts200Data = {
  posts?: Post[];
  pagination?: GetPosts200DataPagination;
};

export type GetPosts200 = {
  success?: boolean;
  message?: string;
  data?: GetPosts200Data;
};

export type PostPostsBodyPostType =
  (typeof PostPostsBodyPostType)[keyof typeof PostPostsBodyPostType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPostsBodyPostType = {
  QUESTION: "QUESTION",
  ANSWER: "ANSWER",
  ANNOUNCEMENT: "ANNOUNCEMENT",
  STUDY_TIP: "STUDY_TIP",
  EXPLANATION: "EXPLANATION",
  RESOURCE: "RESOURCE",
  PDF_RESOURCE: "PDF_RESOURCE",
  SUMMARY: "SUMMARY",
  AI_SUMMARY: "AI_SUMMARY",
  AI_QUESTION: "AI_QUESTION",
  POLL: "POLL",
  DISCUSSION: "DISCUSSION",
  EVENT: "EVENT",
} as const;

export type PostPostsBody = {
  /** @maxLength 150 */
  title?: string;
  /** @minLength 10 */
  content: string;
  postType?: PostPostsBodyPostType;
};

export type PostPosts201 = {
  success?: boolean;
  message?: string;
  data?: Post;
};

export type GetPostsId200 = {
  success?: boolean;
  message?: string;
  data?: Post;
};

export type PutPostsIdBodyPostType =
  (typeof PutPostsIdBodyPostType)[keyof typeof PutPostsIdBodyPostType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsIdBodyPostType = {
  QUESTION: "QUESTION",
  ANSWER: "ANSWER",
  ANNOUNCEMENT: "ANNOUNCEMENT",
  STUDY_TIP: "STUDY_TIP",
  EXPLANATION: "EXPLANATION",
  RESOURCE: "RESOURCE",
  PDF_RESOURCE: "PDF_RESOURCE",
  SUMMARY: "SUMMARY",
  AI_SUMMARY: "AI_SUMMARY",
  AI_QUESTION: "AI_QUESTION",
  POLL: "POLL",
  DISCUSSION: "DISCUSSION",
  EVENT: "EVENT",
} as const;

export type PutPostsIdBody = {
  /** @maxLength 150 */
  title?: string;
  /** @minLength 10 */
  content?: string;
  postType?: PutPostsIdBodyPostType;
};

export type PutPostsId200 = {
  success?: boolean;
  message?: string;
  data?: Post;
};

export type DeletePostsId200 = {
  success?: boolean;
  message?: string;
  data?: Post;
};

export type GetReactionEntityIdEntityTypeParams = {
  /**
   * Cursor for pagination
   */
  cursor?: string;
  /**
   * Number of items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetReactionEntityIdEntityType200DataPagination = {
  hasNextPage?: boolean;
  /** @nullable */
  nextCursor?: string | null;
  count?: number;
};

export type GetReactionEntityIdEntityType200Data = {
  reactions?: Reaction[];
  pagination?: GetReactionEntityIdEntityType200DataPagination;
};

export type GetReactionEntityIdEntityType200 = {
  success?: boolean;
  message?: string;
  data?: GetReactionEntityIdEntityType200Data;
};

export type PostReactionEntityIdEntityTypeBodyReactionType =
  (typeof PostReactionEntityIdEntityTypeBodyReactionType)[keyof typeof PostReactionEntityIdEntityTypeBodyReactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostReactionEntityIdEntityTypeBodyReactionType = {
  LIKE: "LIKE",
  HELPFUL: "HELPFUL",
  EASY: "EASY",
  TOUGH: "TOUGH",
  FIRE: "FIRE",
  MIND_BLOWN: "MIND_BLOWN",
} as const;

export type PostReactionEntityIdEntityTypeBody = {
  reactionType: PostReactionEntityIdEntityTypeBodyReactionType;
};

export type PostReactionEntityIdEntityType201 = {
  success?: boolean;
  message?: string;
  data?: Reaction;
};

export type GetReactionIdReaction200 = {
  success?: boolean;
  message?: string;
  data?: Reaction;
};

export type GetSpecialty200 = {
  success?: boolean;
  message?: string;
  data?: Specialty[];
};

export type PostSpecialtyBody = {
  name: string;
  shortName?: string;
  description?: string;
  facultyId: string;
};

export type PostSpecialty201 = {
  success?: boolean;
  message?: string;
  data?: Specialty;
};

export type GetSpecialtyId200 = {
  success?: boolean;
  message?: string;
  data?: Specialty;
};

export type PutSpecialtyIdBody = {
  name?: string;
  shortName?: string;
  description?: string;
  facultyId?: string;
};

export type PutSpecialtyId200 = {
  success?: boolean;
  message?: string;
  data?: Specialty;
};

export type DeleteSpecialtyId200 = {
  success?: boolean;
  message?: string;
};

export type GetUniversity200 = {
  success?: boolean;
  message?: string;
  data?: University[];
};

export type PostUniversityBody = {
  exampleProperty?: string;
};

export type PostUniversity201 = {
  success?: boolean;
  message?: string;
  data?: University;
};

export type GetUniversityId200 = {
  success?: boolean;
  message?: string;
  data?: University;
};

export type PutUniversityIdBody = {
  exampleProperty?: string;
};

export type PutUniversityId200 = {
  success?: boolean;
  message?: string;
  data?: University;
};

export type DeleteUniversityId200 = {
  success?: boolean;
  message?: string;
};

export type GetUserParams = {
  /**
   * Cursor for pagination
   */
  cursor?: string;
  /**
   * Number of items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetUser200DataPagination = {
  hasNextPage?: boolean;
  /** @nullable */
  nextCursor?: string | null;
  count?: number;
};

export type GetUser200Data = {
  users?: User[];
  pagination?: GetUser200DataPagination;
};

export type GetUser200 = {
  success?: boolean;
  message?: string;
  data?: GetUser200Data;
};

export type GetUserId200 = {
  success?: boolean;
  message?: string;
  data?: User;
};

export type PutUserIdBody = {
  profileImageFile?: Blob;
  /** @maxLength 25 */
  firstName?: string;
  /** @maxLength 25 */
  lastName?: string;
  /**
   * @minLength 3
   * @maxLength 25
   */
  username?: string;
  /** @maxLength 200 */
  bio?: string;
};

export type PutUserId200 = {
  success?: boolean;
  message?: string;
  data?: User;
};

export type PutUserUpdatePasswordBody = {
  /**
   * New password
   * @minLength 8
   */
  password: string;
};

export type PutUserUpdatePassword200 = {
  success?: boolean;
  message?: string;
  data?: User;
};

export type PutUserAcademicYearIdBodyAcademicYear =
  (typeof PutUserAcademicYearIdBodyAcademicYear)[keyof typeof PutUserAcademicYearIdBodyAcademicYear];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutUserAcademicYearIdBodyAcademicYear = {
  L1: "L1",
  L2: "L2",
  L3: "L3",
  M1: "M1",
  M2: "M2",
  D1: "D1",
  D2: "D2",
  D3: "D3",
  D4: "D4",
  D5: "D5",
} as const;

export type PutUserAcademicYearIdBody = {
  academicYear: PutUserAcademicYearIdBodyAcademicYear;
};

export type PutUserAcademicYearId200 = {
  success?: boolean;
  message?: string;
  data?: User;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class EduConnectClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  /**
   * @summary Register a new user
   */
  postAuthSignUp(
    postAuthSignUpBody: PostAuthSignUpBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AuthResponse;
  } {
    const url = new URL(this.cleanBaseUrl + `/auth/sign-up`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postAuthSignUpBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Log in a user
   */
  postAuthLogin(
    postAuthLoginBody: PostAuthLoginBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AuthResponse;
  } {
    const url = new URL(this.cleanBaseUrl + `/auth/login`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postAuthLoginBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Logout user
   */
  postAuthLogout(
    postAuthLogoutBody: PostAuthLogoutBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/auth/logout`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postAuthLogoutBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Logout user from all devices
   */
  postAuthLogoutAllDevices(requestParameters?: Params): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/auth/logout-all-devices`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Refresh access token
   */
  postAuthRefreshToken(requestParameters?: Params): {
    response: Response;
    data: PostAuthRefreshToken201;
  } {
    const url = new URL(this.cleanBaseUrl + `/auth/refresh-token`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Example protected route
   */
  getAuthProtectedRoute(requestParameters?: Params): {
    response: Response;
    data: string;
  } {
    const url = new URL(this.cleanBaseUrl + `/auth/protected-route`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve all Comments for a specific post
   */
  getCommentPostPostIdComments(
    postId: string,
    params?: GetCommentPostPostIdCommentsParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetCommentPostPostIdComments200;
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/comment/post/${postId}/comments` +
      `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve a single Comment by ID
   */
  getCommentId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetCommentId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/comment/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update an existing Comment
   */
  putCommentId(
    id: string,
    putCommentIdBody: PutCommentIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutCommentId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/comment/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putCommentIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Delete a Comment record
   */
  deleteCommentId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DeleteCommentId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/comment/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Create a new Comment
   */
  postCommentPostId(
    postId: string,
    postCommentPostIdBody: PostCommentPostIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PostCommentPostId201;
  } {
    const url = new URL(this.cleanBaseUrl + `/comment/${postId}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postCommentPostIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve all Facultys
   */
  getFaculty(requestParameters?: Params): {
    response: Response;
    data: GetFaculty200;
  } {
    const url = new URL(this.cleanBaseUrl + `/faculty`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Create a new Faculty
   */
  postFaculty(
    postFacultyBody: PostFacultyBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PostFaculty201;
  } {
    const url = new URL(this.cleanBaseUrl + `/faculty`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postFacultyBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve a single Faculty by ID
   */
  getFacultyId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetFacultyId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/faculty/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update an existing Faculty
   */
  putFacultyId(
    id: string,
    putFacultyIdBody: PutFacultyIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutFacultyId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/faculty/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putFacultyIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Delete a Faculty record
   */
  deleteFacultyId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DeleteFacultyId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/faculty/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve all Posts
   */
  getPosts(
    params?: GetPostsParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetPosts200;
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/posts` +
      `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Create a new Post
   */
  postPosts(
    postPostsBody: PostPostsBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PostPosts201;
  } {
    const url = new URL(this.cleanBaseUrl + `/posts`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postPostsBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve a single Post by ID
   */
  getPostsId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetPostsId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/posts/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update an existing Post
   */
  putPostsId(
    id: string,
    putPostsIdBody: PutPostsIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutPostsId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/posts/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putPostsIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Delete a Post record
   */
  deletePostsId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DeletePostsId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/posts/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve all Reactions for a specific Post or Comment
   */
  getReactionEntityIdEntityType(
    entityId: string,
    entityType: "POST" | "COMMENT",
    params?: GetReactionEntityIdEntityTypeParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetReactionEntityIdEntityType200;
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/reaction/${entityId}/${entityType}` +
      `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * If a reaction of the same type by the same user already exists, it will be removed (toggled off). If a different reaction type exists, it will be updated.
   * @summary Create or Toggle a Reaction for a Post or Comment
   */
  postReactionEntityIdEntityType(
    entityId: string,
    entityType: "POST" | "COMMENT",
    postReactionEntityIdEntityTypeBody: PostReactionEntityIdEntityTypeBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PostReactionEntityIdEntityType201;
  } {
    const url = new URL(
      this.cleanBaseUrl + `/reaction/${entityId}/${entityType}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postReactionEntityIdEntityTypeBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve a single Reaction by ID
   */
  getReactionIdReaction(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetReactionIdReaction200;
  } {
    const url = new URL(this.cleanBaseUrl + `/reaction/${id}/reaction`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve all Specialties
   */
  getSpecialty(requestParameters?: Params): {
    response: Response;
    data: GetSpecialty200;
  } {
    const url = new URL(this.cleanBaseUrl + `/specialty`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Create a new Specialty
   */
  postSpecialty(
    postSpecialtyBody: PostSpecialtyBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PostSpecialty201;
  } {
    const url = new URL(this.cleanBaseUrl + `/specialty`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postSpecialtyBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve a single Specialty by ID
   */
  getSpecialtyId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetSpecialtyId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/specialty/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update an existing Specialty
   */
  putSpecialtyId(
    id: string,
    putSpecialtyIdBody: PutSpecialtyIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutSpecialtyId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/specialty/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putSpecialtyIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Delete a Specialty record
   */
  deleteSpecialtyId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DeleteSpecialtyId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/specialty/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve all Universitys
   */
  getUniversity(requestParameters?: Params): {
    response: Response;
    data: GetUniversity200;
  } {
    const url = new URL(this.cleanBaseUrl + `/university`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Create a new University
   */
  postUniversity(
    postUniversityBody: PostUniversityBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PostUniversity201;
  } {
    const url = new URL(this.cleanBaseUrl + `/university`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postUniversityBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve a single University by ID
   */
  getUniversityId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetUniversityId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/university/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update an existing University
   */
  putUniversityId(
    id: string,
    putUniversityIdBody: PutUniversityIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutUniversityId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/university/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putUniversityIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Delete a University record
   */
  deleteUniversityId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DeleteUniversityId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/university/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve all users
   */
  getUser(
    params?: GetUserParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetUser200;
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/user` +
      `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Retrieve a single user by ID
   */
  getUserId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: GetUserId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/user/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update an existing user
   */
  putUserId(
    id: string,
    putUserIdBody: PutUserIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutUserId200;
  } {
    const formData = new FormData();
    if (putUserIdBody.profileImageFile !== undefined) {
      formData.append(`profileImageFile`, putUserIdBody.profileImageFile);
    }
    if (putUserIdBody.firstName !== undefined) {
      formData.append(`firstName`, putUserIdBody.firstName);
    }
    if (putUserIdBody.lastName !== undefined) {
      formData.append(`lastName`, putUserIdBody.lastName);
    }
    if (putUserIdBody.username !== undefined) {
      formData.append(`username`, putUserIdBody.username);
    }
    if (putUserIdBody.bio !== undefined) {
      formData.append(`bio`, putUserIdBody.bio);
    }

    const url = new URL(this.cleanBaseUrl + `/user/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("PUT", url.toString(), formData.body(), {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        "Content-Type": "multipart/form-data; boundary=" + formData.boundary,
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update user password
   */
  putUserUpdatePassword(
    putUserUpdatePasswordBody: PutUserUpdatePasswordBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutUserUpdatePassword200;
  } {
    const url = new URL(this.cleanBaseUrl + `/user/update-password`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putUserUpdatePasswordBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update user academic year
   */
  putUserAcademicYearId(
    id: string,
    putUserAcademicYearIdBody: PutUserAcademicYearIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: PutUserAcademicYearId200;
  } {
    const url = new URL(this.cleanBaseUrl + `/user/academic-year/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putUserAcademicYearIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}


export default function () {
  EduConnectClient.getUser();
}