-- CreateTable
CREATE TABLE `post` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(150) NULL,
    `content` TEXT NOT NULL,
    `postType` ENUM('QUESTION', 'ANSWER', 'ANNOUNCEMENT', 'STUDY_TIP', 'EXPLANATION', 'RESOURCE', 'PDF_RESOURCE', 'SUMMARY', 'AI_SUMMARY', 'AI_QUESTION', 'POLL', 'DISCUSSION', 'EVENT') NOT NULL DEFAULT 'DISCUSSION',
    `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `post` ADD CONSTRAINT `post_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
